prometheus:
  replicas: 1
  affinity: 
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: ch.viseca.metadata.node/role
            operator: In
            values:
            - infra
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: ch.viseca.metadata.node/role
            operator: In
            values:
            - infra
        topologyKey: kubernetes.io/hostname
