prometheus:
  initImage: docker.io/alpine:3.12
  image: quay.io/prometheus/prometheus:v2.27.1
  replicas: 1
  affinity: 
    # nodeAntiAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #     nodeSelectorTerms:
    #     - matchExpressions:
    #       - key: ch.viseca.metadata.node/role
    #         operator: In
    #         values:
    #         - infra
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: ch.viseca.metadata.node/role
            operator: In
            values:
            - infra
        topologyKey: kubernetes.io/hostname
  resources:
    requests:
      cpu: 100m
      memory: 512Mi

nodeExporter:
  image: quay.io/prometheus/node-exporter:v1.1.2
  affinity: 
    #nodeAffinity:
    #  requiredDuringSchedulingIgnoredDuringExecution:
    #    nodeSelectorTerms:
    #    - matchExpressions:
    #      - key: ch.viseca.metadata.node/role
    #        operator: In
    #        values:
    #        - infra
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: ch.viseca.metadata.node/role
            operator: In
            values:
            - infra
        topologyKey: kubernetes.io/hostname
  resources:
    requests:
      cpu: 10m
      memory: 24Mi
    limits:
      cpu: 200m
      memory: 100Mi
  tolerations:
    - effect: NoSchedule
      operator: Exists

kubeStateMetrics:
  image: k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.0.0
  replicas: 1
  affinity: 
    # nodeAffinity:
    #   requiredDuringSchedulingIgnoredDuringExecution:
    #     nodeSelectorTerms:
    #     - matchExpressions:
    #       - key: ch.viseca.metadata.node/role
    #         operator: In
    #         values:
    #         - infra
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: ch.viseca.metadata.node/role
            operator: In
            values:
            - infra
        topologyKey: kubernetes.io/hostname
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 200m
      memory: 150Mi